[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
advent = { version = "1.0.0", path = "../advent" }
dbg-pls = { version = "0.4.3", features = ["derive", "pretty"] }
nom = "7.1.3"
pretty = "0.12.3"
